[package]
name = "smthgood"
version = "1.0.0"
authors = []

[addresses]
ticket_seller_addr = '8d04c2dc796847e0b9283943a0986171c3c0149cd42a4bc97eb3afb03d6c673b'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
