[package]
name = "ticket_seller"
version = "1.0.0"
authors = []

[addresses]
ticket_seller_addr='7948e24ad25a7092cc76a17abf5a741e51f13eb16ead6245eb5cd96284ea09f2'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
